name: Android CI

on:
  push:
    branches: [ "develop" ]
jobs:
  build_apk:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create github.properties file
        run: |
          touch github.properties
          echo gpr.usr=${{ secrets.GPR_USER }} >> github.properties
          echo gpr.key=${{ secrets.GPR_API_KEY }} >> github.properties
          echo "cat github.properties"
          cat github.properties
      - name: Retrieve App name
        run: |
          echo "::set-output name=APP_NAME::$(${{github.workspace}}/gradlew -q appName)"
        id: app_name
      - name: Set App name
        run: |
          echo "APP_NAME=${{steps.app_name.outputs.APP_NAME}}" >> $GITHUB_ENV
      - name: Retrieve Version name
        run: |
          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew -q versionName)"
        id: app_version
      - name: Set Version name
        run: |
          echo "VERSION_NAME=${{steps.app_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.APP_NAME}}
          path: app/build/outputs/apk/debug/${{env.APP_NAME}}-debug.apk
  release:
    name: Release APK
    needs: build_apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: app/build/outputs/apk/debug/${{env.APP_NAME}}-debug.apk
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.VERSION_NAME}}
          release_name: Release  ${{env.VERSION_NAME}}

      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/${{env.APP_NAME}}-debug.apk
          asset_name: ${{env.APP_NAME}}-debug.apk
          asset_content_type: application/zip
