name: Android CI

on:
  push:
    branches: [ "develop" ]
jobs:
  build_apk:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Create github.properties file
      run: |
        touch github.properties
        echo gpr.usr=${{ secrets.GPR_USER }} >> github.properties
        echo gpr.key=${{ secrets.GPR_API_KEY }} >> github.properties
        echo "cat github.properties"
        cat github.properties
    - name: Build with Gradle
      run: ./gradlew build
    - name: Retrieve App name
      run: |
        run: echo "APP_NAME=$(${{github.workspace}}/gradlew -q appName)" >> $GITHUB_ENV
      id: app_name
    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.APP_NAME }}
        path: app/build/outputs/apk/debug/${{ env.APP_NAME }}.apk
  release:
    name: Release APK
    needs: build_apk
    runs-on: ubuntu-latest
    steps:
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: app/build/outputs/apk/debug/${{steps.app_version.outputs.APP_NAME}}.apk
      - name: Retrieve Tag
        run: |
          run: echo "VERSION_NAME=$(${{github.workspace}}/gradlew -q versionName)" >> $GITHUB_ENV
        id: app_version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION_NAME }}
          release_name: Release  ${{ env.VERSION_NAME }}

      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: apk/${{ env.APP_NAME }}.apk
          asset_name: ${{ env.APP_NAME }}.apk
          asset_content_type: application/zip
