name: Test Candidate

on:
  push:
    branches-ignore:
      - 'master'
      - 'develop'
jobs:
  build_apk:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Create github.properties file
        run: |
          touch github.properties
          echo gpr.usr=${{ secrets.GPR_USER }} >> github.properties
          echo gpr.key=${{ secrets.GPR_API_KEY }} >> github.properties
          echo "cat github.properties"
          cat github.properties
      - name: Retrieve App name
        run: |
          echo "::set-output name=APP_NAME::$(${{github.workspace}}/gradlew -q appName)"
        id: app_name
      - name: Set App name
        run: |
          echo "APP_NAME=${{steps.app_name.outputs.APP_NAME}}" >> $GITHUB_ENV
      - name: Set Test Candidate name
        run: |
          echo "TEST_CANDIDATE_NAME=${{env.APP_NAME}}.${{github.run_number}}-debug.apk" >> $GITHUB_ENV
      - name: Retrieve Version name
        run: |
          echo "::set-output name=VERSION_NAME::$(${{github.workspace}}/gradlew -q versionName)"
        id: app_version
      - name: Set Version name
        run: |
          echo "VERSION_NAME=${{steps.app_version.outputs.VERSION_NAME}}" >> $GITHUB_ENV
      - name: Build with Gradle
        run: ./gradlew build -PversionName=${{env.VERSION_NAME}}.${{github.run_number}}
      - name: Rename output file
        run: mv "app/build/outputs/apk/debug/${{env.APP_NAME}}-debug.apk" "app/build/outputs/apk/debug/${{env.TEST_CANDIDATE_NAME}}"
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: ${{env.TEST_CANDIDATE_NAME}}
          path: app/build/outputs/apk/debug/${{env.TEST_CANDIDATE_NAME}}
